"""add TEST type to donate_status

Revision ID: 1cee41f1a917
Revises: a307c5a70c19
Create Date: 2026-04-27 13:41:02.953138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cee41f1a917'
down_revision: Union[str, None] = 'a307c5a70c19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE donatestatus ADD VALUE IF NOT EXISTS 'TEST' AFTER 'NOT_ACTIVE'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
