"""add triumph_increment_transactions table

Revision ID: 22e4b665bb20
Revises: e5c5252a80b9
Create Date: 2026-06-24 14:34:22.223330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22e4b665bb20'
down_revision: Union[str, None] = 'e5c5252a80b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('triumph_increment_transactions',
    sa.Column('amount', sa.Numeric(precision=18, scale=6), server_default=sa.text('0.0'), nullable=False),
    sa.Column('telegram_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['telegram_user_id'], ['telegram_users.id'], name=op.f('fk_triumph_increment_transactions_telegram_user_id_telegram_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_triumph_increment_transactions'))
    )
    op.create_index(op.f('ix_triumph_increment_transactions_id'), 'triumph_increment_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_triumph_increment_transactions_telegram_user_id'), 'triumph_increment_transactions', ['telegram_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_triumph_increment_transactions_telegram_user_id'), table_name='triumph_increment_transactions')
    op.drop_index(op.f('ix_triumph_increment_transactions_id'), table_name='triumph_increment_transactions')
    op.drop_table('triumph_increment_transactions')
    # ### end Alembic commands ###
