"""add total_donates_sum field to AdminStat

Revision ID: 50aa11835922
Revises: 4e8fa96b03ec
Create Date: 2026-06-26 11:09:48.723438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50aa11835922'
down_revision: Union[str, None] = '4e8fa96b03ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_statistic', sa.Column('total_donates_sum', sa.Numeric(precision=18, scale=6), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_statistic', 'total_donates_sum')
    # ### end Alembic commands ###
