"""add donates_sum_for_registration field

Revision ID: 5d53d32219ab
Revises: 50aa11835922
Create Date: 2026-06-29 12:00:25.171410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d53d32219ab'
down_revision: Union[str, None] = '50aa11835922'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_users', sa.Column('donates_sum_for_registration', sa.Integer(), server_default=sa.text('0'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_users', 'donates_sum_for_registration')
    # ### end Alembic commands ###
