"""fix unique ref link indx

Revision ID: 687d3c883ce6
Revises: b55a493228fa
Create Date: 2026-07-08 12:20:34.893165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '687d3c883ce6'
down_revision: Union[str, None] = 'b55a493228fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_referral_links_telegram_user_id'), 'referral_links', type_='unique')
    op.create_index('idx_unique_active_link_per_user', 'referral_links', ['telegram_user_id'], unique=True, postgresql_where=sa.text('is_active = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_unique_active_link_per_user', table_name='referral_links', postgresql_where=sa.text('is_active = true'))
    op.create_unique_constraint(op.f('uq_referral_links_telegram_user_id'), 'referral_links', ['telegram_user_id', 'is_active'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
