"""Add MatrixStat table

Revision ID: 773c8bb62e56
Revises: b162a32d2c33
Create Date: 2026-06-15 16:17:50.935717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '773c8bb62e56'
down_revision: Union[str, None] = 'b162a32d2c33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matrix_statistic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activation_count', sa.Integer(), nullable=False),
    sa.CheckConstraint('id = 1', name=op.f('ck_matrix_statistic_matrix_statistic_singleton')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matrix_statistic'))
    )
    op.execute("""
        INSERT INTO matrix_statistic (id, activation_count)
        VALUES (1, 0)
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matrix_statistic')
    # ### end Alembic commands ###
