"""added nanoid field

Revision ID: 9098d90eb475
Revises: 687d3c883ce6
Create Date: 2026-07-08 17:24:51.178958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9098d90eb475'
down_revision: Union[str, None] = '687d3c883ce6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referral_links', sa.Column('code', sa.String(length=10), nullable=False))
    op.create_index(op.f('ix_referral_links_code'), 'referral_links', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_referral_links_code'), table_name='referral_links')
    op.drop_column('referral_links', 'code')
    # ### end Alembic commands ###
