"""triumph_system_bill

Revision ID: 9ea89eb1fa26
Revises: 05472b4ff833
Create Date: 2026-05-25 14:27:35.149567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ea89eb1fa26'
down_revision: Union[str, None] = '05472b4ff833'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_statistic', sa.Column('triumph_system_bill', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_statistic', 'triumph_system_bill')
    # ### end Alembic commands ###
