"""start_at contest update indexes

Revision ID: 9fc4b453b589
Revises: b57210da8ad8
Create Date: 2026-05-31 22:48:12.533795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fc4b453b589'
down_revision: Union[str, None] = 'b57210da8ad8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registration_contest_start_datetime'), table_name='registration_contests')
    op.drop_constraint(op.f('uq_registration_contests_start_datetime'), 'registration_contests', type_='unique')
    op.create_index(op.f('ix_registration_contests_start_at'), 'registration_contests', ['start_at'], unique=True)
    op.drop_index(op.f('ix_sponsors_contest_start_datetime'), table_name='sponsors_contests')
    op.drop_constraint(op.f('uq_sponsors_contests_start_datetime'), 'sponsors_contests', type_='unique')
    op.create_index(op.f('ix_sponsors_contests_start_at'), 'sponsors_contests', ['start_at'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sponsors_contests_start_at'), table_name='sponsors_contests')
    op.create_unique_constraint(op.f('uq_sponsors_contests_start_datetime'), 'sponsors_contests', ['start_at'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_sponsors_contest_start_datetime'), 'sponsors_contests', ['start_at'], unique=False)
    op.drop_index(op.f('ix_registration_contests_start_at'), table_name='registration_contests')
    op.create_unique_constraint(op.f('uq_registration_contests_start_datetime'), 'registration_contests', ['start_at'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_registration_contest_start_datetime'), 'registration_contests', ['start_at'], unique=False)
    # ### end Alembic commands ###
