"""add count to SponsorsContestPoint

Revision ID: b298ff2e4abf
Revises: 9378da703c00
Create Date: 2026-07-01 07:03:32.513173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b298ff2e4abf'
down_revision: Union[str, None] = '9378da703c00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sponsors_contest_points', sa.Column('count', sa.Integer(), server_default=sa.text('1'), nullable=True))
    op.create_index(op.f('ix_sponsors_contest_points_count'), 'sponsors_contest_points', ['count'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sponsors_contest_points_count'), table_name='sponsors_contest_points')
    op.drop_column('sponsors_contest_points', 'count')
    # ### end Alembic commands ###
