"""add_processed_crypto_bot_payment_webhooks

Revision ID: bb6e38d0e375
Revises: d3d848871b79
Create Date: 2026-06-08 11:47:48.791137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb6e38d0e375'
down_revision: Union[str, None] = 'd3d848871b79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_crypto_bot_payment_webhooks',
    sa.Column('update_id', sa.BigInteger(), nullable=True),
    sa.Column('update_type', sa.String(length=50), nullable=False),
    sa.Column('request_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processed_crypto_bot_payment_webhooks'))
    )
    op.create_index(op.f('ix_processed_crypto_bot_payment_webhooks_id'), 'processed_crypto_bot_payment_webhooks', ['id'], unique=False)
    op.create_index(op.f('ix_processed_crypto_bot_payment_webhooks_update_id'), 'processed_crypto_bot_payment_webhooks', ['update_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processed_crypto_bot_payment_webhooks_update_id'), table_name='processed_crypto_bot_payment_webhooks')
    op.drop_index(op.f('ix_processed_crypto_bot_payment_webhooks_id'), table_name='processed_crypto_bot_payment_webhooks')
    op.drop_table('processed_crypto_bot_payment_webhooks')
    # ### end Alembic commands ###
