"""add admin statistic table

Revision ID: c7da728df689
Revises: 06fb5770881e
Create Date: 2026-05-16 11:59:36.216888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7da728df689'
down_revision: Union[str, None] = '06fb5770881e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_statistic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_bill', sa.BigInteger(), server_default=sa.text('0'), nullable=True),
    sa.Column('donates_for_registration', sa.BigInteger(), server_default=sa.text('0'), nullable=True),
    sa.CheckConstraint('id = 1', name='admin_statistic_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("""
        INSERT INTO admin_statistic (id, system_bill, donates_for_registration)
        VALUES (1, 0, 0)
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_statistic')
    # ### end Alembic commands ###
