"""remove matrix_tasks table

Revision ID: e5c5252a80b9
Revises: 47f78d9866d5
Create Date: 2026-06-22 17:21:10.347087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5c5252a80b9'
down_revision: Union[str, None] = '47f78d9866d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_add_to_matrix_tasks_engine_type'), table_name='add_to_matrix_tasks')
    op.drop_index(op.f('ix_add_to_matrix_tasks_execute_at'), table_name='add_to_matrix_tasks')
    op.drop_index(op.f('ix_add_to_matrix_tasks_id'), table_name='add_to_matrix_tasks')
    op.drop_index(op.f('ix_add_to_matrix_tasks_is_executed'), table_name='add_to_matrix_tasks')
    op.drop_index(op.f('ix_add_to_matrix_tasks_obj_id'), table_name='add_to_matrix_tasks')
    op.drop_table('add_to_matrix_tasks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('add_to_matrix_tasks',
    sa.Column('execute_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_executed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('donate_sum', sa.NUMERIC(precision=18, scale=6), autoincrement=False, nullable=True),
    sa.Column('obj_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('engine_type', postgresql.ENUM('JSON', 'NODES', name='matrixenginetype'), server_default=sa.text("'JSON'::matrixenginetype"), autoincrement=False, nullable=False),
    sa.Column('create_donates', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_add_to_matrix_tasks'))
    )
    op.create_index(op.f('ix_add_to_matrix_tasks_obj_id'), 'add_to_matrix_tasks', ['obj_id'], unique=False)
    op.create_index(op.f('ix_add_to_matrix_tasks_is_executed'), 'add_to_matrix_tasks', ['is_executed'], unique=False)
    op.create_index(op.f('ix_add_to_matrix_tasks_id'), 'add_to_matrix_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_add_to_matrix_tasks_execute_at'), 'add_to_matrix_tasks', ['execute_at'], unique=False)
    op.create_index(op.f('ix_add_to_matrix_tasks_engine_type'), 'add_to_matrix_tasks', ['engine_type'], unique=False)
    # ### end Alembic commands ###
