"""registration_stat

Revision ID: f6632455f65b
Revises: 773c8bb62e56
Create Date: 2026-06-16 11:38:07.489465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6632455f65b'
down_revision: Union[str, None] = '773c8bb62e56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registration_statistic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.CheckConstraint('id = 1', name=op.f('ck_registration_statistic_registration_statistic_singleton')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_registration_statistic'))
    )
    op.execute("""
        INSERT INTO registration_statistic (id, count)
       VALUES (1, 0)
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registration_statistic')
    # ### end Alembic commands ###
