upstream fastapi {
    server api:8000;
}

server {
    listen 80;
    server_name code-deneg.duckdns.org;

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name code-deneg.duckdns.org;

    ssl_certificate /etc/letsencrypt/live/code-deneg.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/code-deneg.duckdns.org/privkey.pem;

    location / {
        proxy_pass http://fastapi;
        include proxy_params;
    }
}
