"""captcha_verified and is_donate_for_registration_sent

Revision ID: 0531cc3e8221
Revises: c7da728df689
Create Date: 2026-05-20 11:43:03.688908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0531cc3e8221'
down_revision: Union[str, None] = 'c7da728df689'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_users', sa.Column('captcha_verified', sa.Boolean(), nullable=True))
    op.add_column('telegram_users', sa.Column('is_donate_for_registration_sent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_users', 'is_donate_for_registration_sent')
    op.drop_column('telegram_users', 'captcha_verified')
    # ### end Alembic commands ###
