"""Add init_prize_fund to contest

Revision ID: 06fb5770881e
Revises: 5fe1a2265226
Create Date: 2026-05-14 16:40:15.490165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06fb5770881e'
down_revision: Union[str, None] = '5fe1a2265226'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sponsors_contests', sa.Column('init_prize_fund', sa.Integer(), server_default=sa.text('100'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sponsors_contests', 'init_prize_fund')
    # ### end Alembic commands ###
