"""split bill

Revision ID: 151b90af870b
Revises: 2324c1053fe1
Create Date: 2026-04-16 19:17:17.990186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '151b90af870b'
down_revision: Union[str, None] = '2324c1053fe1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_users', sa.Column('bill_for_activation', sa.Float(), nullable=True))
    op.add_column('telegram_users', sa.Column('bill_for_withdraw', sa.Float(), nullable=True))
    op.drop_column('telegram_users', 'bill')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_users', sa.Column('bill', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('telegram_users', 'bill_for_withdraw')
    op.drop_column('telegram_users', 'bill_for_activation')
    # ### end Alembic commands ###
