"""add send_donate_to_global_safe field

Revision ID: 1e546cb338ba
Revises: d85469bebc0b
Create Date: 2026-09-01 16:53:26.900858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e546cb338ba'
down_revision: Union[str, None] = 'd85469bebc0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'telegram_users',
        sa.Column('send_donate_to_global_safe', sa.Boolean(),
                  server_default=sa.text('True'),
                  nullable=True
                  )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_users', 'send_donate_to_global_safe')
    # ### end Alembic commands ###