"""update donate statuses

Revision ID: 2324c1053fe1
Revises: ed47ec7258db
Create Date: 2026-04-15 05:55:20.330374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2324c1053fe1'
down_revision: Union[str, None] = 'ed47ec7258db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE donatestatus ADD VALUE 'GOLD'")
        op.execute("ALTER TYPE donatestatus ADD VALUE 'PLATINUM'")
        op.execute("ALTER TYPE donatestatus ADD VALUE 'BRILLIANT'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
