"""Add Sponsors Contest

Revision ID: 31cbde078b3a
Revises: f4c5fb20c12b
Create Date: 2026-05-09 17:38:07.588044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31cbde078b3a'
down_revision: Union[str, None] = 'f4c5fb20c12b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sponsors_contests',
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sponsors_contests_id'), 'sponsors_contests', ['id'], unique=False)
    op.create_table('sponsors_contest_points',
    sa.Column('sponsor_user_id', sa.BigInteger(), nullable=True),
    sa.Column('contest_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['contest_id'], ['sponsors_contests.id'], ),
    sa.ForeignKeyConstraint(['sponsor_user_id'], ['telegram_users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sponsors_contest_points_contest_id'), 'sponsors_contest_points', ['contest_id'], unique=False)
    op.create_index(op.f('ix_sponsors_contest_points_id'), 'sponsors_contest_points', ['id'], unique=False)
    op.create_index(op.f('ix_sponsors_contest_points_sponsor_user_id'), 'sponsors_contest_points', ['sponsor_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sponsors_contest_points_sponsor_user_id'), table_name='sponsors_contest_points')
    op.drop_index(op.f('ix_sponsors_contest_points_id'), table_name='sponsors_contest_points')
    op.drop_index(op.f('ix_sponsors_contest_points_contest_id'), table_name='sponsors_contest_points')
    op.drop_table('sponsors_contest_points')
    op.drop_index(op.f('ix_sponsors_contests_id'), table_name='sponsors_contests')
    op.drop_table('sponsors_contests')
    # ### end Alembic commands ###
