"""added global status to matrix

Revision ID: 45a748678693
Revises: 66c5637130dd
Create Date: 2026-08-14 17:03:27.256403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45a748678693'
down_revision: Union[str, None] = '66c5637130dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

matrix_marketing_type_enum = sa.Enum(
    'START',
    'GLOBAL',
    name='matrixmarketingtype',
    schema='public',
)

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    matrix_marketing_type_enum.create(
        op.get_bind(),
        checkfirst=True,
    )
    op.add_column('matrices', sa.Column('marketing_type', matrix_marketing_type_enum, server_default=sa.text("'START'"), nullable=False))
    op.add_column('matrices', sa.Column('global_marketing_status', sa.Enum('NOT_ACTIVE', 'SEPTEMBER', 'OCTOBER', 'NOVEMBER', 'DECEMBER', 'JANUARY', 'FEBRUARY', 'MARCH', 'APRIL', 'MAY', 'JUNE', 'JULY', 'AUGUST', name='globalmarketingdonatestatus'), nullable=True))
    op.create_index(op.f('ix_matrices_global_marketing_status'), 'matrices', ['global_marketing_status'], unique=False)
    op.create_index(op.f('ix_matrices_marketing_type'), 'matrices', ['marketing_type'], unique=False)
    op.create_check_constraint(
   op.f('ck_matrices_ck_matrix_marketing_engine'),
   'matrices',
   "\n  (\n  marketing_type = 'START'\n  AND engine_type IN ('JSON', 'NODES')\n  AND status IS NOT NULL\n  AND global_marketing_status IS NULL\n  )\n  OR\n  (\n  marketing_type = 'GLOBAL'\n  AND engine_type = 'NODES'\n  AND status IS NULL\n  AND global_marketing_status IS NOT NULL\n  )\n  ")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_matrices_ck_matrix_marketing_engine'), 'matrices', type_='check')
    op.drop_index(op.f('ix_matrices_marketing_type'), table_name='matrices')
    op.drop_index(op.f('ix_matrices_global_marketing_status'), table_name='matrices')
    op.drop_column('matrices', 'global_marketing_status')
    op.drop_column('matrices', 'marketing_type')
    matrix_marketing_type_enum.drop(
        op.get_bind(),
        checkfirst=True,
    )
    # ### end Alembic commands ###