"""add_global_safe

Revision ID: 4b3580f5a143
Revises: fbdcb212a0ce
Create Date: 2026-08-23 17:15:58.956829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b3580f5a143'
down_revision: Union[str, None] = 'fbdcb212a0ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_users', sa.Column('global_safe', sa.Numeric(precision=18, scale=6), server_default=sa.text('0.0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_users', 'global_safe')
    # ### end Alembic commands ###