"""add triumph_bill_transactions table

Revision ID: 4e8fa96b03ec
Revises: e5c5252a80b9
Create Date: 2026-06-24 15:53:10.519893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e8fa96b03ec'
down_revision: Union[str, None] = 'e5c5252a80b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('triumph_bill_transactions',
    sa.Column('amount', sa.Numeric(precision=18, scale=6), server_default=sa.text('0.0'), nullable=False),
    sa.Column('type_', sa.Enum('INCREMENT', 'DECREMENT', name='triumphbilltransactiontype'), nullable=False),
    sa.Column('telegram_user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['telegram_user_id'], ['telegram_users.id'], name=op.f('fk_triumph_bill_transactions_telegram_user_id_telegram_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_triumph_bill_transactions'))
    )
    op.create_index(op.f('ix_triumph_bill_transactions_id'), 'triumph_bill_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_triumph_bill_transactions_telegram_user_id'), 'triumph_bill_transactions', ['telegram_user_id'], unique=False)
    op.create_index(op.f('ix_triumph_bill_transactions_type_'), 'triumph_bill_transactions', ['type_'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_triumph_bill_transactions_type_'), table_name='triumph_bill_transactions')
    op.drop_index(op.f('ix_triumph_bill_transactions_telegram_user_id'), table_name='triumph_bill_transactions')
    op.drop_index(op.f('ix_triumph_bill_transactions_id'), table_name='triumph_bill_transactions')
    op.drop_table('triumph_bill_transactions')
    op.execute("DROP TYPE IF EXISTS triumphbilltransactiontype")
    # ### end Alembic commands ###
