"""Add prize_fund to contest

Revision ID: 5fe1a2265226
Revises: 89d35e535e36
Create Date: 2026-05-14 15:33:00.775917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fe1a2265226'
down_revision: Union[str, None] = '89d35e535e36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sponsors_contests', sa.Column('prize_fund', sa.Integer(), server_default=sa.text('100'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sponsors_contests', 'prize_fund')
    # ### end Alembic commands ###
