"""remove_is_confirmed_and_is_canceled_from_donate

Revision ID: 61b6b89b3ef8
Revises: 6b82b20d61f2
Create Date: 2026-03-31 14:58:57.523772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61b6b89b3ef8'
down_revision: Union[str, None] = '6b82b20d61f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('donate_transactions', 'is_confirmed')
    op.drop_column('donate_transactions', 'is_canceled')
    op.drop_column('donates', 'is_confirmed')
    op.drop_column('donates', 'is_canceled')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donates', sa.Column('is_canceled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('donates', sa.Column('is_confirmed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('donate_transactions', sa.Column('is_canceled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('donate_transactions', sa.Column('is_confirmed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
