"""add_WithdrawalRequest_model

Revision ID: 67abdf32410e
Revises: 61b6b89b3ef8
Create Date: 2026-04-06 14:44:54.157590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67abdf32410e'
down_revision: Union[str, None] = '61b6b89b3ef8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('withdrawal_requests',
    sa.Column('telegram_user_id', sa.UUID(), nullable=True),
    sa.Column('tokens_count', sa.Integer(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['telegram_user_id'], ['telegram_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_withdrawal_requests_id'), 'withdrawal_requests', ['id'], unique=False)
    op.create_index(op.f('ix_withdrawal_requests_is_paid'), 'withdrawal_requests', ['is_paid'], unique=False)
    op.create_index(op.f('ix_withdrawal_requests_telegram_user_id'), 'withdrawal_requests', ['telegram_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_withdrawal_requests_telegram_user_id'), table_name='withdrawal_requests')
    op.drop_index(op.f('ix_withdrawal_requests_is_paid'), table_name='withdrawal_requests')
    op.drop_index(op.f('ix_withdrawal_requests_id'), table_name='withdrawal_requests')
    op.drop_table('withdrawal_requests')
    # ### end Alembic commands ###
