"""initial

Revision ID: 6b82b20d61f2
Revises: 
Create Date: 2026-03-29 13:55:31.381010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b82b20d61f2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user',
    sa.Column('login', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_user_id'), 'admin_user', ['id'], unique=False)
    op.create_table('telegram_users',
    sa.Column('status', sa.Enum('NOT_ACTIVE', 'BASE', 'BRONZE', 'SILVER', name='donatestatus'), nullable=True),
    sa.Column('sponsor_user_id', sa.BigInteger(), nullable=True),
    sa.Column('invites_count', sa.Integer(), nullable=True),
    sa.Column('donates_sum', sa.Float(), nullable=True),
    sa.Column('bill', sa.Float(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('wallet_address', sa.String(), nullable=True),
    sa.Column('depth_level', sa.Integer(), nullable=True),
    sa.Column('is_banned', sa.Boolean(), nullable=True),
    sa.Column('is_bot', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['sponsor_user_id'], ['telegram_users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='unique_user_id')
    )
    op.create_index(op.f('ix_telegram_users_id'), 'telegram_users', ['id'], unique=False)
    op.create_index(op.f('ix_telegram_users_is_admin'), 'telegram_users', ['is_admin'], unique=False)
    op.create_index(op.f('ix_telegram_users_sponsor_user_id'), 'telegram_users', ['sponsor_user_id'], unique=False)
    op.create_index(op.f('ix_telegram_users_user_id'), 'telegram_users', ['user_id'], unique=True)
    op.create_table('matrices',
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('NOT_ACTIVE', 'BASE', 'BRONZE', 'SILVER', name='donatestatus'), nullable=True),
    sa.Column('matrices', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('matrix_telegram_usernames', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('telegram_users', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['telegram_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matrices_id'), 'matrices', ['id'], unique=False)
    op.create_index(op.f('ix_matrices_matrices'), 'matrices', ['matrices'], unique=False)
    op.create_index(op.f('ix_matrices_matrix_telegram_usernames'), 'matrices', ['matrix_telegram_usernames'], unique=False)
    op.create_index(op.f('ix_matrices_owner_id'), 'matrices', ['owner_id'], unique=False)
    op.create_index(op.f('ix_matrices_status'), 'matrices', ['status'], unique=False)
    op.create_index(op.f('ix_matrices_telegram_users'), 'matrices', ['telegram_users'], unique=False)
    op.create_table('transactions',
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('telegram_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['telegram_user_id'], ['telegram_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_table('donates',
    sa.Column('telegram_user_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=True),
    sa.Column('is_canceled', sa.Boolean(), nullable=True),
    sa.Column('matrix_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['matrix_id'], ['matrices.id'], ),
    sa.ForeignKeyConstraint(['telegram_user_id'], ['telegram_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donates_id'), 'donates', ['id'], unique=False)
    op.create_index(op.f('ix_donates_matrix_id'), 'donates', ['matrix_id'], unique=False)
    op.create_index(op.f('ix_donates_telegram_user_id'), 'donates', ['telegram_user_id'], unique=False)
    op.create_table('donate_transactions',
    sa.Column('sponsor_id', sa.UUID(), nullable=True),
    sa.Column('donate_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=True),
    sa.Column('is_canceled', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['donate_id'], ['donates.id'], ),
    sa.ForeignKeyConstraint(['sponsor_id'], ['telegram_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donate_transactions_donate_id'), 'donate_transactions', ['donate_id'], unique=False)
    op.create_index(op.f('ix_donate_transactions_id'), 'donate_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_donate_transactions_sponsor_id'), 'donate_transactions', ['sponsor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_donate_transactions_sponsor_id'), table_name='donate_transactions')
    op.drop_index(op.f('ix_donate_transactions_id'), table_name='donate_transactions')
    op.drop_index(op.f('ix_donate_transactions_donate_id'), table_name='donate_transactions')
    op.drop_table('donate_transactions')
    op.drop_index(op.f('ix_donates_telegram_user_id'), table_name='donates')
    op.drop_index(op.f('ix_donates_matrix_id'), table_name='donates')
    op.drop_index(op.f('ix_donates_id'), table_name='donates')
    op.drop_table('donates')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_matrices_telegram_users'), table_name='matrices')
    op.drop_index(op.f('ix_matrices_status'), table_name='matrices')
    op.drop_index(op.f('ix_matrices_owner_id'), table_name='matrices')
    op.drop_index(op.f('ix_matrices_matrix_telegram_usernames'), table_name='matrices')
    op.drop_index(op.f('ix_matrices_matrices'), table_name='matrices')
    op.drop_index(op.f('ix_matrices_id'), table_name='matrices')
    op.drop_table('matrices')
    op.drop_index(op.f('ix_telegram_users_user_id'), table_name='telegram_users')
    op.drop_index(op.f('ix_telegram_users_sponsor_user_id'), table_name='telegram_users')
    op.drop_index(op.f('ix_telegram_users_is_admin'), table_name='telegram_users')
    op.drop_index(op.f('ix_telegram_users_id'), table_name='telegram_users')
    op.drop_table('telegram_users')
    op.drop_index(op.f('ix_admin_user_id'), table_name='admin_user')
    op.drop_table('admin_user')
    # ### end Alembic commands ###
