"""add top_10 to contest

Revision ID: 70d77c6bb2da
Revises: bc5fec41ffd0
Create Date: 2026-05-10 17:17:29.003034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '70d77c6bb2da'
down_revision: Union[str, None] = 'bc5fec41ffd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sponsors_contests', sa.Column('top_10_rating', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sponsors_contests', 'top_10_rating')
    # ### end Alembic commands ###
