"""add transfer table

Revision ID: 89d35e535e36
Revises: 00b8bf524f81
Create Date: 2026-05-12 13:59:51.622346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89d35e535e36'
down_revision: Union[str, None] = '00b8bf524f81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfers',
    sa.Column('from_id', sa.UUID(), nullable=True),
    sa.Column('to_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_id'], ['telegram_users.id'], ),
    sa.ForeignKeyConstraint(['to_id'], ['telegram_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfers_amount'), 'transfers', ['amount'], unique=False)
    op.create_index(op.f('ix_transfers_from_id'), 'transfers', ['from_id'], unique=False)
    op.create_index(op.f('ix_transfers_id'), 'transfers', ['id'], unique=False)
    op.create_index(op.f('ix_transfers_to_id'), 'transfers', ['to_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transfers_to_id'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_id'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_from_id'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_amount'), table_name='transfers')
    op.drop_table('transfers')
    # ### end Alembic commands ###
