"""registration_contests_models

Revision ID: 8be72375accf
Revises: 33a6993ad213
Create Date: 2026-05-28 14:42:29.662647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8be72375accf'
down_revision: Union[str, None] = '33a6993ad213'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registration_contests',
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('prize_fund', sa.Integer(), server_default=sa.text('100'), nullable=True),
    sa.Column('init_prize_fund', sa.Integer(), server_default=sa.text('100'), nullable=True),
    sa.Column('top_10_rating', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_registration_contests'))
    )
    op.create_index(op.f('ix_registration_contests_id'), 'registration_contests', ['id'], unique=False)
    op.create_index(op.f('ix_registration_contests_results'), 'registration_contests', ['results'], unique=False)
    op.create_index(op.f('ix_registration_contests_start_date'), 'registration_contests', ['start_date'], unique=True)
    op.create_table('registration_contest_points',
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('contest_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['contest_id'], ['registration_contests.id'], name=op.f('fk_registration_contest_points_contest_id_registration_contests')),
    sa.ForeignKeyConstraint(['user_id'], ['telegram_users.user_id'], name=op.f('fk_registration_contest_points_user_id_telegram_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_registration_contest_points'))
    )
    op.create_index(op.f('ix_registration_contest_points_contest_id'), 'registration_contest_points', ['contest_id'], unique=False)
    op.create_index(op.f('ix_registration_contest_points_id'), 'registration_contest_points', ['id'], unique=False)
    op.create_index(op.f('ix_registration_contest_points_user_id'), 'registration_contest_points', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registration_contest_points_user_id'), table_name='registration_contest_points')
    op.drop_index(op.f('ix_registration_contest_points_id'), table_name='registration_contest_points')
    op.drop_index(op.f('ix_registration_contest_points_contest_id'), table_name='registration_contest_points')
    op.drop_table('registration_contest_points')
    op.drop_index(op.f('ix_registration_contests_start_date'), table_name='registration_contests')
    op.drop_index(op.f('ix_registration_contests_results'), table_name='registration_contests')
    op.drop_index(op.f('ix_registration_contests_id'), table_name='registration_contests')
    op.drop_table('registration_contests')
    # ### end Alembic commands ###
