"""add private_channel_link_sent field

Revision ID: 9378da703c00
Revises: 5d53d32219ab
Create Date: 2026-06-29 13:51:48.415469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9378da703c00'
down_revision: Union[str, None] = '5d53d32219ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_users', sa.Column('private_channel_link_sent', sa.Boolean(), server_default=sa.text('False'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_users', 'private_channel_link_sent')
    # ### end Alembic commands ###
