"""add type to doante_trans

Revision ID: a307c5a70c19
Revises: 151b90af870b
Create Date: 2026-04-16 21:48:40.506279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a307c5a70c19'
down_revision: Union[str, None] = '151b90af870b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    CREATE TYPE donate_transaction_enum AS ENUM ('SYSTEM', 'SPONSOR', 'MATRIX')
    """)
    op.add_column('donate_transactions', sa.Column('type_', sa.Enum('SYSTEM', 'SPONSOR', 'MATRIX', name='donate_transaction_enum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('donate_transactions', 'type_')
    # ### end Alembic commands ###
