"""move_from_float_to_decimal

Revision ID: b162a32d2c33
Revises: e98e87c7dc5a
Create Date: 2026-06-13 19:27:04.939469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b162a32d2c33'
down_revision: Union[str, None] = 'e98e87c7dc5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('donate_transactions', 'quantity',
                    existing_type=sa.DOUBLE_PRECISION(precision=53),
                    type_=sa.Numeric(precision=18, scale=6),
                    existing_nullable=True,
                    postgresql_using='quantity::numeric')

    op.alter_column('donates', 'quantity',
                    existing_type=sa.DOUBLE_PRECISION(precision=53),
                    type_=sa.Numeric(precision=18, scale=6),
                    existing_nullable=True,
                    postgresql_using='quantity::numeric')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('donates', 'quantity',
                    existing_type=sa.Numeric(precision=18, scale=6),
                    type_=sa.DOUBLE_PRECISION(precision=53),
                    existing_nullable=True,
                    postgresql_using='quantity::double precision')

    op.alter_column('donate_transactions', 'quantity',
                    existing_type=sa.Numeric(precision=18, scale=6),
                    type_=sa.DOUBLE_PRECISION(precision=53),
                    existing_nullable=True,
                    postgresql_using='quantity::double precision')
    # ### end Alembic commands ###