"""add_WithdrawalRequest_model

Revision ID: b40fe1e26b82
Revises: 67abdf32410e
Create Date: 2026-04-07 14:13:05.690759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b40fe1e26b82'
down_revision: Union[str, None] = '67abdf32410e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('withdrawal_requests', sa.Column('wallet_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('withdrawal_requests', 'wallet_address')
    # ### end Alembic commands ###
