"""add referral_links table

Revision ID: b55a493228fa
Revises: b298ff2e4abf
Create Date: 2026-07-07 17:30:17.061641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b55a493228fa'
down_revision: Union[str, None] = 'b298ff2e4abf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referral_links',
    sa.Column('telegram_user_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['telegram_user_id'], ['telegram_users.id'], name=op.f('fk_referral_links_telegram_user_id_telegram_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_referral_links')),
    sa.UniqueConstraint('telegram_user_id', 'is_active', name=op.f('uq_referral_links_telegram_user_id'))
    )
    op.create_index('idx_active_user_link', 'referral_links', ['telegram_user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_referral_links_id'), 'referral_links', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_referral_links_id'), table_name='referral_links')
    op.drop_index('idx_active_user_link', table_name='referral_links')
    op.drop_table('referral_links')
    # ### end Alembic commands ###
