"""add is_archived to contest

Revision ID: bc5fec41ffd0
Revises: 6aa4dc80a1d4
Create Date: 2026-05-10 13:23:32.762782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc5fec41ffd0'
down_revision: Union[str, None] = '6aa4dc80a1d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sponsors_contests', sa.Column('is_archived', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sponsors_contests', 'is_archived')
    # ### end Alembic commands ###
