"""add  matrix_nodes

Revision ID: c3eaa1f6b9cb
Revises: 0531cc3e8221
Create Date: 2026-05-24 16:47:16.212882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c3eaa1f6b9cb'
down_revision: Union[str, None] = '0531cc3e8221'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matrix_nodes',
    sa.Column('matrix_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('position', sa.BigInteger(), nullable=False),
    sa.Column('children_count', sa.BigInteger(), nullable=True),
    sa.Column('downline_count', sa.BigInteger(), nullable=True),
    sa.Column('last_activation', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['matrix_id'], ['matrices.id'], name=op.f('fk_matrix_nodes_matrix_id_matrices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['telegram_users.id'], name=op.f('fk_matrix_nodes_owner_id_telegram_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matrix_nodes')),
    sa.UniqueConstraint('matrix_id', 'position', name=op.f('uq_matrix_nodes_matrix_id'))
    )
    op.create_index('idx_matrix_free', 'matrix_nodes', ['matrix_id', 'children_count', 'level', 'position'], unique=False)
    op.create_index('idx_user_matrix', 'matrix_nodes', ['owner_id', 'matrix_id'], unique=False)
    op.create_index(op.f('ix_matrix_nodes_id'), 'matrix_nodes', ['id'], unique=False)
    op.create_index(op.f('ix_matrix_nodes_level'), 'matrix_nodes', ['level'], unique=False)
    op.create_index(op.f('ix_matrix_nodes_position'), 'matrix_nodes', ['position'], unique=False)
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'matrixenginetype') THEN
                CREATE TYPE matrixenginetype AS ENUM ('JSON', 'NODES');
            END IF;
        END
        $$;
        """
    )
    op.add_column('donate_transactions', sa.Column('sponsor_depth', sa.Integer(), nullable=True))
    op.add_column('matrices', sa.Column('engine_type', sa.Enum('JSON', 'NODES', name='matrixenginetype'), server_default=sa.text("'JSON'"), nullable=False))
    op.add_column('matrices', sa.Column('closed_places_count', sa.BigInteger(), nullable=True))
    op.add_column('matrices', sa.Column('root_node_id', sa.UUID(), nullable=True))
    op.add_column('matrices', sa.Column('is_closed', sa.Boolean(), nullable=True))
    op.drop_index(op.f('ix_matrices_matrix_telegram_usernames'), table_name='matrices')
    op.create_index(op.f('ix_matrices_engine_type'), 'matrices', ['engine_type'], unique=False)
    op.create_index(op.f('ix_matrices_is_closed'), 'matrices', ['is_closed'], unique=False)
    op.create_foreign_key(op.f('fk_matrices_root_node_id_matrix_nodes'), 'matrices', 'matrix_nodes', ['root_node_id'], ['id'])
    op.drop_column('matrices', 'matrix_telegram_usernames')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matrices', sa.Column('matrix_telegram_usernames', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_matrices_root_node_id_matrix_nodes'), 'matrices', type_='foreignkey')
    op.drop_index(op.f('ix_matrices_is_closed'), table_name='matrices')
    op.drop_index(op.f('ix_matrices_engine_type'), table_name='matrices')
    op.create_index(op.f('ix_matrices_matrix_telegram_usernames'), 'matrices', ['matrix_telegram_usernames'], unique=False)
    op.drop_column('matrices', 'is_closed')
    op.drop_column('matrices', 'root_node_id')
    op.drop_column('matrices', 'closed_places_count')
    op.drop_column('matrices', 'engine_type')
    op.drop_column('donate_transactions', 'sponsor_depth')
    op.drop_index(op.f('ix_matrix_nodes_position'), table_name='matrix_nodes')
    op.drop_index(op.f('ix_matrix_nodes_level'), table_name='matrix_nodes')
    op.drop_index(op.f('ix_matrix_nodes_id'), table_name='matrix_nodes')
    op.drop_index('idx_user_matrix', table_name='matrix_nodes')
    op.drop_index('idx_matrix_free', table_name='matrix_nodes')
    op.drop_table('matrix_nodes')
    op.execute("DROP TYPE IF EXISTS matrixenginetype")
    # ### end Alembic commands ###
