"""indxs fix

Revision ID: c859de7a60a4
Revises: 45a748678693
Create Date: 2026-08-15 15:51:27.445060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c859de7a60a4'
down_revision: Union[str, None] = '45a748678693'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matrices_global_marketing_status'), table_name='matrices')
    op.drop_index(op.f('ix_matrices_status'), table_name='matrices')
    op.create_index('ix_matrices_marketing_type_global_marketing_status', 'matrices', ['marketing_type', 'global_marketing_status'], unique=False)
    op.create_index('ix_matrices_marketing_type_status', 'matrices', ['marketing_type', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_matrices_marketing_type_status', table_name='matrices')
    op.drop_index('ix_matrices_marketing_type_global_marketing_status', table_name='matrices')
    op.create_index(op.f('ix_matrices_status'), 'matrices', ['status'], unique=False)
    op.create_index(op.f('ix_matrices_global_marketing_status'), 'matrices', ['global_marketing_status'], unique=False)
    # ### end Alembic commands ###