"""added create_donates f

Revision ID: d3d848871b79
Revises: 9fc4b453b589
Create Date: 2026-06-06 13:22:54.375430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3d848871b79'
down_revision: Union[str, None] = '9fc4b453b589'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('add_to_matrix_tasks', sa.Column('create_donates', sa.Boolean(), server_default=sa.text('TRUE'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('add_to_matrix_tasks', 'create_donates')
    # ### end Alembic commands ###
