"""rm global_donate_status_from_nodes

Revision ID: d85469bebc0b
Revises: 002a819917a1
Create Date: 2026-08-29 09:35:56.158799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd85469bebc0b'
down_revision: Union[str, None] = '002a819917a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matrix_nodes_global_marketing_status'), table_name='matrix_nodes')
    op.create_index(op.f('ix_matrix_nodes_marketing_type'), 'matrix_nodes', ['marketing_type'], unique=False)
    op.drop_constraint(op.f('ck_matrix_nodes_ck_matrix_node_global_status_logic'), 'matrix_nodes', type_='check')
    op.drop_column('matrix_nodes', 'global_marketing_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matrix_nodes', sa.Column('global_marketing_status', postgresql.ENUM('SEPTEMBER', 'OCTOBER', 'NOVEMBER', 'DECEMBER', 'JANUARY', 'FEBRUARY', 'MARCH', 'APRIL', 'MAY', 'JUNE', 'JULY', 'AUGUST', name='globalmarketingdonatestatus'), autoincrement=False, nullable=True))
    op.create_check_constraint(op.f('ck_matrix_nodes_ck_matrix_node_global_status_logic'), 'matrix_nodes', "marketing_type = 'GLOBAL'::matrixmarketingtype AND global_marketing_status IS NOT NULL OR marketing_type = 'START'::matrixmarketingtype AND global_marketing_status IS NULL")
    op.drop_index(op.f('ix_matrix_nodes_marketing_type'), table_name='matrix_nodes')
    op.create_index(op.f('ix_matrix_nodes_global_marketing_status'), 'matrix_nodes', ['global_marketing_status'], unique=False)
    # ### end Alembic commands ###