"""move_from_float_to_decimal

Revision ID: e98e87c7dc5a
Revises: bb6e38d0e375
Create Date: 2026-06-13 19:15:19.907406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e98e87c7dc5a'
down_revision: Union[str, None] = 'bb6e38d0e375'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('add_to_matrix_tasks', 'donate_sum',
                    existing_type=sa.INTEGER(),
                    type_=sa.Numeric(precision=18, scale=6),
                    existing_nullable=True,
                    postgresql_using='donate_sum::numeric')

    op.alter_column('admin_statistic', 'system_bill',
                    existing_type=sa.DOUBLE_PRECISION(precision=53),
                    type_=sa.Numeric(precision=18, scale=6),
                    existing_nullable=True,
                    postgresql_using='system_bill::numeric')

    op.alter_column('admin_statistic', 'triumph_system_bill',
                    existing_type=sa.DOUBLE_PRECISION(precision=53),
                    type_=sa.Numeric(precision=18, scale=6),
                    existing_nullable=True,
                    postgresql_using='triumph_system_bill::numeric')

    op.alter_column('admin_statistic', 'donates_sum_for_registration',
                    existing_type=sa.DOUBLE_PRECISION(precision=53),
                    type_=sa.Numeric(precision=18, scale=6),
                    existing_nullable=True,
                    existing_server_default=sa.text('0'),
                    postgresql_using='donates_sum_for_registration::numeric')

    op.alter_column('registration_contests', 'prize_fund',
                    existing_type=sa.INTEGER(),
                    type_=sa.Numeric(precision=18, scale=6),
                    existing_nullable=True,
                    existing_server_default=sa.text('100'),
                    postgresql_using='prize_fund::numeric')

    op.alter_column('registration_contests', 'init_prize_fund',
                    existing_type=sa.INTEGER(),
                    type_=sa.Numeric(precision=18, scale=6),
                    existing_nullable=True,
                    existing_server_default=sa.text('100'),
                    postgresql_using='init_prize_fund::numeric')

    op.alter_column('sponsors_contests', 'prize_fund',
                    existing_type=sa.INTEGER(),
                    type_=sa.Numeric(precision=18, scale=6),
                    existing_nullable=True,
                    existing_server_default=sa.text('100'),
                    postgresql_using='prize_fund::numeric')

    op.alter_column('sponsors_contests', 'init_prize_fund',
                    existing_type=sa.INTEGER(),
                    type_=sa.Numeric(precision=18, scale=6),
                    existing_nullable=True,
                    existing_server_default=sa.text('100'),
                    postgresql_using='init_prize_fund::numeric')

    # Для добавления новой колонки явный каст не требуется
    op.add_column('telegram_users', sa.Column('triumph_bill', sa.Numeric(precision=18, scale=6), nullable=True))

    op.alter_column('telegram_users', 'donates_sum',
                    existing_type=sa.DOUBLE_PRECISION(precision=53),
                    type_=sa.Numeric(precision=18, scale=6),
                    existing_nullable=True,
                    postgresql_using='donates_sum::numeric')

    op.alter_column('telegram_users', 'bill_for_activation',
                    existing_type=sa.DOUBLE_PRECISION(precision=53),
                    type_=sa.Numeric(precision=18, scale=6),
                    existing_nullable=True,
                    postgresql_using='bill_for_activation::numeric')

    op.alter_column('telegram_users', 'bill_for_withdraw',
                    existing_type=sa.DOUBLE_PRECISION(precision=53),
                    type_=sa.Numeric(precision=18, scale=6),
                    existing_nullable=True,
                    postgresql_using='bill_for_withdraw::numeric')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('telegram_users', 'bill_for_withdraw',
                    existing_type=sa.Numeric(precision=18, scale=6),
                    type_=sa.DOUBLE_PRECISION(precision=53),
                    existing_nullable=True,
                    postgresql_using='bill_for_withdraw::double precision')

    op.alter_column('telegram_users', 'bill_for_activation',
                    existing_type=sa.Numeric(precision=18, scale=6),
                    type_=sa.DOUBLE_PRECISION(precision=53),
                    existing_nullable=True,
                    postgresql_using='bill_for_activation::double precision')

    op.alter_column('telegram_users', 'donates_sum',
                    existing_type=sa.Numeric(precision=18, scale=6),
                    type_=sa.DOUBLE_PRECISION(precision=53),
                    existing_nullable=True,
                    postgresql_using='donates_sum::double precision')

    op.drop_column('telegram_users', 'triumph_bill')

    op.alter_column('sponsors_contests', 'init_prize_fund',
                    existing_type=sa.Numeric(precision=18, scale=6),
                    type_=sa.INTEGER(),
                    existing_nullable=True,
                    existing_server_default=sa.text('100'),
                    postgresql_using='init_prize_fund::integer')

    op.alter_column('sponsors_contests', 'prize_fund',
                    existing_type=sa.Numeric(precision=18, scale=6),
                    type_=sa.INTEGER(),
                    existing_nullable=True,
                    existing_server_default=sa.text('100'),
                    postgresql_using='prize_fund::integer')

    op.alter_column('registration_contests', 'init_prize_fund',
                    existing_type=sa.Numeric(precision=18, scale=6),
                    type_=sa.INTEGER(),
                    existing_nullable=True,
                    existing_server_default=sa.text('100'),
                    postgresql_using='init_prize_fund::integer')

    op.alter_column('registration_contests', 'prize_fund',
                    existing_type=sa.Numeric(precision=18, scale=6),
                    type_=sa.INTEGER(),
                    existing_nullable=True,
                    existing_server_default=sa.text('100'),
                    postgresql_using='prize_fund::integer')

    op.alter_column('admin_statistic', 'donates_sum_for_registration',
                    existing_type=sa.Numeric(precision=18, scale=6),
                    type_=sa.DOUBLE_PRECISION(precision=53),
                    existing_nullable=True,
                    existing_server_default=sa.text('0'),
                    postgresql_using='donates_sum_for_registration::double precision')

    op.alter_column('admin_statistic', 'triumph_system_bill',
                    existing_type=sa.Numeric(precision=18, scale=6),
                    type_=sa.DOUBLE_PRECISION(precision=53),
                    existing_nullable=True,
                    postgresql_using='triumph_system_bill::double precision')

    op.alter_column('admin_statistic', 'system_bill',
                    existing_type=sa.Numeric(precision=18, scale=6),
                    type_=sa.DOUBLE_PRECISION(precision=53),
                    existing_nullable=True,
                    postgresql_using='system_bill::double precision')

    op.alter_column('add_to_matrix_tasks', 'donate_sum',
                    existing_type=sa.Numeric(precision=18, scale=6),
                    type_=sa.INTEGER(),
                    existing_nullable=True,
                    postgresql_using='donate_sum::integer')
    # ### end Alembic commands ###
