"""add_bot_to_matrix_task_model

Revision ID: ed47ec7258db
Revises: b40fe1e26b82
Create Date: 2026-04-13 17:33:23.092647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed47ec7258db'
down_revision: Union[str, None] = 'b40fe1e26b82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('add_to_matrix_tasks',
    sa.Column('execute_at', sa.DateTime(), nullable=True),
    sa.Column('is_executed', sa.Boolean(), nullable=True),
    sa.Column('donate_sum', sa.Integer(), nullable=True),
    sa.Column('matrix_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['matrix_id'], ['matrices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_add_to_matrix_tasks_execute_at'), 'add_to_matrix_tasks', ['execute_at'], unique=False)
    op.create_index(op.f('ix_add_to_matrix_tasks_id'), 'add_to_matrix_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_add_to_matrix_tasks_is_executed'), 'add_to_matrix_tasks', ['is_executed'], unique=False)
    op.create_index(op.f('ix_add_to_matrix_tasks_matrix_id'), 'add_to_matrix_tasks', ['matrix_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_add_to_matrix_tasks_matrix_id'), table_name='add_to_matrix_tasks')
    op.drop_index(op.f('ix_add_to_matrix_tasks_is_executed'), table_name='add_to_matrix_tasks')
    op.drop_index(op.f('ix_add_to_matrix_tasks_id'), table_name='add_to_matrix_tasks')
    op.drop_index(op.f('ix_add_to_matrix_tasks_execute_at'), table_name='add_to_matrix_tasks')
    op.drop_table('add_to_matrix_tasks')
    # ### end Alembic commands ###
