"""Add network

Revision ID: f4c5fb20c12b
Revises: 1cee41f1a917
Create Date: 2026-05-08 19:39:17.747608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4c5fb20c12b'
down_revision: Union[str, None] = '1cee41f1a917'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        CREATE TYPE cryptonetworktype AS ENUM ('TON', 'BEP20', 'SOLANA')
        """)
    op.add_column('withdrawal_requests', sa.Column('network', sa.Enum('TON', 'BEP20', 'SOLANA', name='cryptonetworktype'), server_default='TON', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('withdrawal_requests', 'wallet_address_type')
    # ### end Alembic commands ###
