"""removed not active status

Revision ID: fbdcb212a0ce
Revises: c859de7a60a4
Create Date: 2026-08-17 18:33:36.260008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbdcb212a0ce'
down_revision: Union[str, None] = 'c859de7a60a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


donate_status_enum = sa.Enum(
    'TEST',
    'BASE',
    'BRONZE',
    'SILVER',
    'GOLD',
    'PLATINUM',
    'BRILLIANT',
    name='donatestatus',
)
global_marketing_status_enum = sa.Enum(
    'SEPTEMBER',
    'OCTOBER',
    'NOVEMBER',
    'DECEMBER',
    'JANUARY',
    'FEBRUARY',
    'MARCH',
    'APRIL',
    'MAY',
    'JUNE',
    'JULY',
    'AUGUST',
    name='globalmarketingdonatestatus',
)


def upgrade() -> None:
    # Обновление старых значений
    op.execute("""
               UPDATE matrices
               SET status = NULL
               WHERE status = 'NOT_ACTIVE'
               """)

    op.execute("""
               UPDATE telegram_users
               SET status = NULL
               WHERE status = 'NOT_ACTIVE'
               """)

    op.execute("""
               UPDATE matrices
               SET global_marketing_status = NULL
               WHERE global_marketing_status = 'NOT_ACTIVE'
               """)

    op.execute("""
               UPDATE telegram_users
               SET global_marketing_status = NULL
               WHERE global_marketing_status = 'NOT_ACTIVE'
               """)

    # Переименуем старые типы для пересоздания
    op.execute("""
            ALTER TYPE donatestatus RENAME TO donatestatus_old
        """)
    op.execute("""
            ALTER TYPE globalmarketingdonatestatus RENAME TO globalmarketingdonatestatus_old
        """)

    # Создаем новые типы
    bind = op.get_bind()
    donate_status_enum.create(
        bind=bind,
        checkfirst=True,
    )
    global_marketing_status_enum.create(
        bind=bind,
        checkfirst=True,
    )

    # Назначаем новые типы
    op.execute("""
               ALTER TABLE matrices
               ALTER
               COLUMN status TYPE donatestatus
            USING status::text::donatestatus
               """)

    op.execute("""
               ALTER TABLE telegram_users
               ALTER
               COLUMN status TYPE donatestatus
            USING status::text::donatestatus
               """)

    op.execute("""
               ALTER TABLE matrices
               ALTER
               COLUMN global_marketing_status TYPE globalmarketingdonatestatus
                USING global_marketing_status::text::globalmarketingdonatestatus
               """)

    op.execute("""
               ALTER TABLE telegram_users
               ALTER
               COLUMN global_marketing_status TYPE globalmarketingdonatestatus
                USING global_marketing_status::text::globalmarketingdonatestatus
               """)

    # Удаляем старые типы
    op.execute(
        "DROP TYPE donatestatus_old"
    )
    op.execute(
        "DROP TYPE globalmarketingdonatestatus_old"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###